[package]
name = "phys"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "69249d8b51079734ad894ad9e9952080e1655ac7"}
